# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20160220_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='upvoted_by',
        ),
        migrations.AddField(
            model_name='question',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='question_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
