# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_auto_20160321_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='answer_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
