# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_answers_upvoted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
